POST http://localhost:5000/api/users/login



{
    "email": "praveenramakurthi@gmail.com",
    "password": "praveen"
}

####
PATCH  http://localhost:5000/api/users/profile
{
    "Content-Type": "application/json",
    "x-auth-token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9".eyJfaWQiOiI2Njk2NWU2ZTI5MmYxODZlOTk5N2I5NmYiLCJpYXQiOjE3MjExMzExMjUsImV4cCI6MTcyMTEzNDcyNX0.AKAXDFvBQZozmeG1OiQLRZRlEJpn4BsBabILpOZRP6M

}

{
    "email": "praveen2@gmail.com"
}